// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: matchmakingsvr/match_coc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PitayaGame.MatchMakingSvr {

  /// <summary>Holder for reflection information generated from matchmakingsvr/match_coc.proto</summary>
  public static partial class MatchCocReflection {

    #region Descriptor
    /// <summary>File descriptor for matchmakingsvr/match_coc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MatchCocReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5tYXRjaG1ha2luZ3N2ci9tYXRjaF9jb2MucHJvdG8SDm1hdGNobWFraW5n",
            "c3ZyGhhjb21tb24vdHlwZXMvdHlwZXMucHJvdG8iNwoXR2V0TmV4dENhbmRp",
            "ZGF0ZVJlcXVlc3QSHAoUZXhjbHVkZV9kZWZlbmRlcl9pZHMYASADKAkifwoY",
            "R2V0TmV4dENhbmRpZGF0ZVJlc3BvbnNlEh8KBHJlc3AYASABKAsyES50eXBl",
            "cy5Db21tb25SZXNwEjAKCWNhbmRpZGF0ZRgCIAEoCzIdLm1hdGNobWFraW5n",
            "c3ZyLkNhbmRpZGF0ZURhdGESEAoIbWF0Y2hfaWQYAyABKAMizAEKDUNhbmRp",
            "ZGF0ZURhdGESEwoLZGVmZW5kZXJfaWQYASABKAkSGQoRZGVmZW5kZXJfdXNl",
            "cm5hbWUYAiABKAkSFwoPZGVmZW5kZXJfdHJvcGh5GAMgASgDEhsKE2RlZmVu",
            "ZGVyX2Jhc2VfcG93ZXIYBCABKAUSNwoNYmFzZV9zbmFwc2hvdBgFIAEoCzIg",
            "Lm1hdGNobWFraW5nc3ZyLkJhc2VTbmFwc2hvdFZpZXcSHAoUc25hcHNob3Rf",
            "dXBkYXRlX3RpbWUYBiABKAMiPwoQQmFzZVNuYXBzaG90VmlldxITCgtsYXlv",
            "dXRfZGF0YRgBIAEoDBIWCg5sYXlvdXRfdmVyc2lvbhgCIAEoBSIUChJDYW5j",
            "ZWxNYXRjaFJlcXVlc3QiNgoTQ2FuY2VsTWF0Y2hSZXNwb25zZRIfCgRyZXNw",
            "GAEgASgLMhEudHlwZXMuQ29tbW9uUmVzcEJaWjxwaXRheWEtZ2FtZS9wcm90",
            "b3MvcGIvZ29sYW5nL21hdGNobWFraW5nc3ZyO21hdGNobWFraW5nc3ZycGKq",
            "AhlQaXRheWFHYW1lLk1hdGNoTWFraW5nU3ZyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::PitayaGame.Types.TypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PitayaGame.MatchMakingSvr.GetNextCandidateRequest), global::PitayaGame.MatchMakingSvr.GetNextCandidateRequest.Parser, new[]{ "ExcludeDefenderIds" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PitayaGame.MatchMakingSvr.GetNextCandidateResponse), global::PitayaGame.MatchMakingSvr.GetNextCandidateResponse.Parser, new[]{ "Resp", "Candidate", "MatchId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PitayaGame.MatchMakingSvr.CandidateData), global::PitayaGame.MatchMakingSvr.CandidateData.Parser, new[]{ "DefenderId", "DefenderUsername", "DefenderTrophy", "DefenderBasePower", "BaseSnapshot", "SnapshotUpdateTime" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PitayaGame.MatchMakingSvr.BaseSnapshotView), global::PitayaGame.MatchMakingSvr.BaseSnapshotView.Parser, new[]{ "LayoutData", "LayoutVersion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PitayaGame.MatchMakingSvr.CancelMatchRequest), global::PitayaGame.MatchMakingSvr.CancelMatchRequest.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PitayaGame.MatchMakingSvr.CancelMatchResponse), global::PitayaGame.MatchMakingSvr.CancelMatchResponse.Parser, new[]{ "Resp" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 获取下一个匹配候选
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetNextCandidateRequest : pb::IMessage<GetNextCandidateRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetNextCandidateRequest> _parser = new pb::MessageParser<GetNextCandidateRequest>(() => new GetNextCandidateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetNextCandidateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PitayaGame.MatchMakingSvr.MatchCocReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetNextCandidateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetNextCandidateRequest(GetNextCandidateRequest other) : this() {
      excludeDefenderIds_ = other.excludeDefenderIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetNextCandidateRequest Clone() {
      return new GetNextCandidateRequest(this);
    }

    /// <summary>Field number for the "exclude_defender_ids" field.</summary>
    public const int ExcludeDefenderIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_excludeDefenderIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> excludeDefenderIds_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// 排除的防御者ID列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ExcludeDefenderIds {
      get { return excludeDefenderIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetNextCandidateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetNextCandidateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!excludeDefenderIds_.Equals(other.excludeDefenderIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= excludeDefenderIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      excludeDefenderIds_.WriteTo(output, _repeated_excludeDefenderIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      excludeDefenderIds_.WriteTo(ref output, _repeated_excludeDefenderIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += excludeDefenderIds_.CalculateSize(_repeated_excludeDefenderIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetNextCandidateRequest other) {
      if (other == null) {
        return;
      }
      excludeDefenderIds_.Add(other.excludeDefenderIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            excludeDefenderIds_.AddEntriesFrom(input, _repeated_excludeDefenderIds_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            excludeDefenderIds_.AddEntriesFrom(ref input, _repeated_excludeDefenderIds_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GetNextCandidateResponse : pb::IMessage<GetNextCandidateResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetNextCandidateResponse> _parser = new pb::MessageParser<GetNextCandidateResponse>(() => new GetNextCandidateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetNextCandidateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PitayaGame.MatchMakingSvr.MatchCocReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetNextCandidateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetNextCandidateResponse(GetNextCandidateResponse other) : this() {
      resp_ = other.resp_ != null ? other.resp_.Clone() : null;
      candidate_ = other.candidate_ != null ? other.candidate_.Clone() : null;
      matchId_ = other.matchId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetNextCandidateResponse Clone() {
      return new GetNextCandidateResponse(this);
    }

    /// <summary>Field number for the "resp" field.</summary>
    public const int RespFieldNumber = 1;
    private global::PitayaGame.Types.CommonResp resp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PitayaGame.Types.CommonResp Resp {
      get { return resp_; }
      set {
        resp_ = value;
      }
    }

    /// <summary>Field number for the "candidate" field.</summary>
    public const int CandidateFieldNumber = 2;
    private global::PitayaGame.MatchMakingSvr.CandidateData candidate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PitayaGame.MatchMakingSvr.CandidateData Candidate {
      get { return candidate_; }
      set {
        candidate_ = value;
      }
    }

    /// <summary>Field number for the "match_id" field.</summary>
    public const int MatchIdFieldNumber = 3;
    private long matchId_;
    /// <summary>
    /// 匹配ID（创建占用记录时生成，用于战斗服务识别客户端选择的匹配，且必须是该攻击者自己刷出来的）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MatchId {
      get { return matchId_; }
      set {
        matchId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetNextCandidateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetNextCandidateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Resp, other.Resp)) return false;
      if (!object.Equals(Candidate, other.Candidate)) return false;
      if (MatchId != other.MatchId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resp_ != null) hash ^= Resp.GetHashCode();
      if (candidate_ != null) hash ^= Candidate.GetHashCode();
      if (MatchId != 0L) hash ^= MatchId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resp);
      }
      if (candidate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Candidate);
      }
      if (MatchId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MatchId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resp);
      }
      if (candidate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Candidate);
      }
      if (MatchId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MatchId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resp);
      }
      if (candidate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Candidate);
      }
      if (MatchId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MatchId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetNextCandidateResponse other) {
      if (other == null) {
        return;
      }
      if (other.resp_ != null) {
        if (resp_ == null) {
          Resp = new global::PitayaGame.Types.CommonResp();
        }
        Resp.MergeFrom(other.Resp);
      }
      if (other.candidate_ != null) {
        if (candidate_ == null) {
          Candidate = new global::PitayaGame.MatchMakingSvr.CandidateData();
        }
        Candidate.MergeFrom(other.Candidate);
      }
      if (other.MatchId != 0L) {
        MatchId = other.MatchId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resp_ == null) {
              Resp = new global::PitayaGame.Types.CommonResp();
            }
            input.ReadMessage(Resp);
            break;
          }
          case 18: {
            if (candidate_ == null) {
              Candidate = new global::PitayaGame.MatchMakingSvr.CandidateData();
            }
            input.ReadMessage(Candidate);
            break;
          }
          case 24: {
            MatchId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resp_ == null) {
              Resp = new global::PitayaGame.Types.CommonResp();
            }
            input.ReadMessage(Resp);
            break;
          }
          case 18: {
            if (candidate_ == null) {
              Candidate = new global::PitayaGame.MatchMakingSvr.CandidateData();
            }
            input.ReadMessage(Candidate);
            break;
          }
          case 24: {
            MatchId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 候选对手（服务端已排除受保护目标）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CandidateData : pb::IMessage<CandidateData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CandidateData> _parser = new pb::MessageParser<CandidateData>(() => new CandidateData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CandidateData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PitayaGame.MatchMakingSvr.MatchCocReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CandidateData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CandidateData(CandidateData other) : this() {
      defenderId_ = other.defenderId_;
      defenderUsername_ = other.defenderUsername_;
      defenderTrophy_ = other.defenderTrophy_;
      defenderBasePower_ = other.defenderBasePower_;
      baseSnapshot_ = other.baseSnapshot_ != null ? other.baseSnapshot_.Clone() : null;
      snapshotUpdateTime_ = other.snapshotUpdateTime_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CandidateData Clone() {
      return new CandidateData(this);
    }

    /// <summary>Field number for the "defender_id" field.</summary>
    public const int DefenderIdFieldNumber = 1;
    private string defenderId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefenderId {
      get { return defenderId_; }
      set {
        defenderId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "defender_username" field.</summary>
    public const int DefenderUsernameFieldNumber = 2;
    private string defenderUsername_ = "";
    /// <summary>
    /// 可选：未接入用户服务前可回传ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DefenderUsername {
      get { return defenderUsername_; }
      set {
        defenderUsername_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "defender_trophy" field.</summary>
    public const int DefenderTrophyFieldNumber = 3;
    private long defenderTrophy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DefenderTrophy {
      get { return defenderTrophy_; }
      set {
        defenderTrophy_ = value;
      }
    }

    /// <summary>Field number for the "defender_base_power" field.</summary>
    public const int DefenderBasePowerFieldNumber = 4;
    private int defenderBasePower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DefenderBasePower {
      get { return defenderBasePower_; }
      set {
        defenderBasePower_ = value;
      }
    }

    /// <summary>Field number for the "base_snapshot" field.</summary>
    public const int BaseSnapshotFieldNumber = 5;
    private global::PitayaGame.MatchMakingSvr.BaseSnapshotView baseSnapshot_;
    /// <summary>
    /// 基地布局快照
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PitayaGame.MatchMakingSvr.BaseSnapshotView BaseSnapshot {
      get { return baseSnapshot_; }
      set {
        baseSnapshot_ = value;
      }
    }

    /// <summary>Field number for the "snapshot_update_time" field.</summary>
    public const int SnapshotUpdateTimeFieldNumber = 6;
    private long snapshotUpdateTime_;
    /// <summary>
    /// Unix秒（BaseSnapshot.updated_at）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SnapshotUpdateTime {
      get { return snapshotUpdateTime_; }
      set {
        snapshotUpdateTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CandidateData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CandidateData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DefenderId != other.DefenderId) return false;
      if (DefenderUsername != other.DefenderUsername) return false;
      if (DefenderTrophy != other.DefenderTrophy) return false;
      if (DefenderBasePower != other.DefenderBasePower) return false;
      if (!object.Equals(BaseSnapshot, other.BaseSnapshot)) return false;
      if (SnapshotUpdateTime != other.SnapshotUpdateTime) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DefenderId.Length != 0) hash ^= DefenderId.GetHashCode();
      if (DefenderUsername.Length != 0) hash ^= DefenderUsername.GetHashCode();
      if (DefenderTrophy != 0L) hash ^= DefenderTrophy.GetHashCode();
      if (DefenderBasePower != 0) hash ^= DefenderBasePower.GetHashCode();
      if (baseSnapshot_ != null) hash ^= BaseSnapshot.GetHashCode();
      if (SnapshotUpdateTime != 0L) hash ^= SnapshotUpdateTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DefenderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DefenderId);
      }
      if (DefenderUsername.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DefenderUsername);
      }
      if (DefenderTrophy != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DefenderTrophy);
      }
      if (DefenderBasePower != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DefenderBasePower);
      }
      if (baseSnapshot_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(BaseSnapshot);
      }
      if (SnapshotUpdateTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SnapshotUpdateTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DefenderId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DefenderId);
      }
      if (DefenderUsername.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DefenderUsername);
      }
      if (DefenderTrophy != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(DefenderTrophy);
      }
      if (DefenderBasePower != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(DefenderBasePower);
      }
      if (baseSnapshot_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(BaseSnapshot);
      }
      if (SnapshotUpdateTime != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SnapshotUpdateTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DefenderId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefenderId);
      }
      if (DefenderUsername.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DefenderUsername);
      }
      if (DefenderTrophy != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DefenderTrophy);
      }
      if (DefenderBasePower != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DefenderBasePower);
      }
      if (baseSnapshot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BaseSnapshot);
      }
      if (SnapshotUpdateTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SnapshotUpdateTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CandidateData other) {
      if (other == null) {
        return;
      }
      if (other.DefenderId.Length != 0) {
        DefenderId = other.DefenderId;
      }
      if (other.DefenderUsername.Length != 0) {
        DefenderUsername = other.DefenderUsername;
      }
      if (other.DefenderTrophy != 0L) {
        DefenderTrophy = other.DefenderTrophy;
      }
      if (other.DefenderBasePower != 0) {
        DefenderBasePower = other.DefenderBasePower;
      }
      if (other.baseSnapshot_ != null) {
        if (baseSnapshot_ == null) {
          BaseSnapshot = new global::PitayaGame.MatchMakingSvr.BaseSnapshotView();
        }
        BaseSnapshot.MergeFrom(other.BaseSnapshot);
      }
      if (other.SnapshotUpdateTime != 0L) {
        SnapshotUpdateTime = other.SnapshotUpdateTime;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DefenderId = input.ReadString();
            break;
          }
          case 18: {
            DefenderUsername = input.ReadString();
            break;
          }
          case 24: {
            DefenderTrophy = input.ReadInt64();
            break;
          }
          case 32: {
            DefenderBasePower = input.ReadInt32();
            break;
          }
          case 42: {
            if (baseSnapshot_ == null) {
              BaseSnapshot = new global::PitayaGame.MatchMakingSvr.BaseSnapshotView();
            }
            input.ReadMessage(BaseSnapshot);
            break;
          }
          case 48: {
            SnapshotUpdateTime = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DefenderId = input.ReadString();
            break;
          }
          case 18: {
            DefenderUsername = input.ReadString();
            break;
          }
          case 24: {
            DefenderTrophy = input.ReadInt64();
            break;
          }
          case 32: {
            DefenderBasePower = input.ReadInt32();
            break;
          }
          case 42: {
            if (baseSnapshot_ == null) {
              BaseSnapshot = new global::PitayaGame.MatchMakingSvr.BaseSnapshotView();
            }
            input.ReadMessage(BaseSnapshot);
            break;
          }
          case 48: {
            SnapshotUpdateTime = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 基地快照视图（从 BaseSnapshot 透传，默认 bytes 承载 JSON/压缩串）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BaseSnapshotView : pb::IMessage<BaseSnapshotView>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BaseSnapshotView> _parser = new pb::MessageParser<BaseSnapshotView>(() => new BaseSnapshotView());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BaseSnapshotView> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PitayaGame.MatchMakingSvr.MatchCocReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSnapshotView() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSnapshotView(BaseSnapshotView other) : this() {
      layoutData_ = other.layoutData_;
      layoutVersion_ = other.layoutVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BaseSnapshotView Clone() {
      return new BaseSnapshotView(this);
    }

    /// <summary>Field number for the "layout_data" field.</summary>
    public const int LayoutDataFieldNumber = 1;
    private pb::ByteString layoutData_ = pb::ByteString.Empty;
    /// <summary>
    /// BaseSnapshot.base_data（JSON或压缩）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString LayoutData {
      get { return layoutData_; }
      set {
        layoutData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "layout_version" field.</summary>
    public const int LayoutVersionFieldNumber = 2;
    private int layoutVersion_;
    /// <summary>
    /// 与客户端约定的布局版本
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LayoutVersion {
      get { return layoutVersion_; }
      set {
        layoutVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BaseSnapshotView);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BaseSnapshotView other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LayoutData != other.LayoutData) return false;
      if (LayoutVersion != other.LayoutVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LayoutData.Length != 0) hash ^= LayoutData.GetHashCode();
      if (LayoutVersion != 0) hash ^= LayoutVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LayoutData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(LayoutData);
      }
      if (LayoutVersion != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LayoutVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LayoutData.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(LayoutData);
      }
      if (LayoutVersion != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LayoutVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LayoutData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(LayoutData);
      }
      if (LayoutVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LayoutVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BaseSnapshotView other) {
      if (other == null) {
        return;
      }
      if (other.LayoutData.Length != 0) {
        LayoutData = other.LayoutData;
      }
      if (other.LayoutVersion != 0) {
        LayoutVersion = other.LayoutVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LayoutData = input.ReadBytes();
            break;
          }
          case 16: {
            LayoutVersion = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LayoutData = input.ReadBytes();
            break;
          }
          case 16: {
            LayoutVersion = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 取消匹配（玩家放弃所有通过 GetNextCandidate 锁定的匹配，删除所有 pending 匹配记录）
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CancelMatchRequest : pb::IMessage<CancelMatchRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CancelMatchRequest> _parser = new pb::MessageParser<CancelMatchRequest>(() => new CancelMatchRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CancelMatchRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PitayaGame.MatchMakingSvr.MatchCocReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelMatchRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelMatchRequest(CancelMatchRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelMatchRequest Clone() {
      return new CancelMatchRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CancelMatchRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CancelMatchRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CancelMatchRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CancelMatchResponse : pb::IMessage<CancelMatchResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CancelMatchResponse> _parser = new pb::MessageParser<CancelMatchResponse>(() => new CancelMatchResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CancelMatchResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::PitayaGame.MatchMakingSvr.MatchCocReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelMatchResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelMatchResponse(CancelMatchResponse other) : this() {
      resp_ = other.resp_ != null ? other.resp_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CancelMatchResponse Clone() {
      return new CancelMatchResponse(this);
    }

    /// <summary>Field number for the "resp" field.</summary>
    public const int RespFieldNumber = 1;
    private global::PitayaGame.Types.CommonResp resp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::PitayaGame.Types.CommonResp Resp {
      get { return resp_; }
      set {
        resp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CancelMatchResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CancelMatchResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Resp, other.Resp)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resp_ != null) hash ^= Resp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Resp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CancelMatchResponse other) {
      if (other == null) {
        return;
      }
      if (other.resp_ != null) {
        if (resp_ == null) {
          Resp = new global::PitayaGame.Types.CommonResp();
        }
        Resp.MergeFrom(other.Resp);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resp_ == null) {
              Resp = new global::PitayaGame.Types.CommonResp();
            }
            input.ReadMessage(Resp);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resp_ == null) {
              Resp = new global::PitayaGame.Types.CommonResp();
            }
            input.ReadMessage(Resp);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
