
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class BuffTable : Luban.BeanBase
{
    public BuffTable(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("Name");
        Icon = (string)_obj.GetValue("Icon");
        Des = (string)_obj.GetValue("Des");
        Show = (bool)_obj.GetValue("Show");
        { var __json0 = _obj.GetValue("Buff_effect"); BuffEffect = new System.Collections.Generic.List<EffectNode>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { EffectNode __v0;  __v0 = global::cfg.EffectNode.DeserializeEffectNode(__e0);  BuffEffect.Add(__v0); }   }
        ReFlash = (bool)_obj.GetValue("ReFlash");
        TickCd = (int)_obj.GetValue("TickCd");
        BaseCalType = (EBaseCalculateType)(int)_obj.GetValue("BaseCalType");
        FirstGoal = (ECampType)(int)_obj.GetValue("FirstGoal");
        NextGoal = (ETargetType)(int)_obj.GetValue("NextGoal");
        Time = (int)_obj.GetValue("Time");
        Overlay = (bool)_obj.GetValue("Overlay");
        Priority = (int)_obj.GetValue("Priority");
        Isdebuff = (bool)_obj.GetValue("Isdebuff");
        BuffFX = (string)_obj.GetValue("Buff_FX");
    }

    public static BuffTable DeserializeBuffTable(JToken _buf)
    {
        return new BuffTable(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 是否在状态栏展示
    /// </summary>
    public readonly bool Show;
    /// <summary>
    /// 效果
    /// </summary>
    public readonly System.Collections.Generic.List<EffectNode> BuffEffect;
    /// <summary>
    /// 是否刷新
    /// </summary>
    public readonly bool ReFlash;
    /// <summary>
    /// Tick间隔
    /// </summary>
    public readonly int TickCd;
    /// <summary>
    /// 基本运算类型
    /// </summary>
    public readonly EBaseCalculateType BaseCalType;
    /// <summary>
    /// 首选目标
    /// </summary>
    public readonly ECampType FirstGoal;
    /// <summary>
    /// 次选目标
    /// </summary>
    public readonly ETargetType NextGoal;
    /// <summary>
    /// 持续时间（0是瞬发，-1是永久）
    /// </summary>
    public readonly int Time;
    /// <summary>
    /// 是否可以叠加
    /// </summary>
    public readonly bool Overlay;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否是debuff
    /// </summary>
    public readonly bool Isdebuff;
    /// <summary>
    /// buff特效预制体名
    /// </summary>
    public readonly string BuffFX;


    public const int __ID__ = 2049267483;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in BuffEffect) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "Icon:" + Icon + ","
        + "Des:" + Des + ","
        + "Show:" + Show + ","
        + "BuffEffect:" + Luban.StringUtil.CollectionToString(BuffEffect) + ","
        + "ReFlash:" + ReFlash + ","
        + "TickCd:" + TickCd + ","
        + "BaseCalType:" + BaseCalType + ","
        + "FirstGoal:" + FirstGoal + ","
        + "NextGoal:" + NextGoal + ","
        + "Time:" + Time + ","
        + "Overlay:" + Overlay + ","
        + "Priority:" + Priority + ","
        + "Isdebuff:" + Isdebuff + ","
        + "BuffFX:" + BuffFX + ","
        + "}";
    }
}
}

