
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Config : Luban.BeanBase
{
    public Config(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Key = (string)_obj.GetValue("Key");
        Value = (string)_obj.GetValue("Value");
        Desc = (string)_obj.GetValue("Desc");
    }

    public static Config DeserializeConfig(JToken _buf)
    {
        return new Config(_buf);
    }

    public readonly string Key;
    public readonly string Value;
    public readonly string Desc;


    public const int __ID__ = 2024042338;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "Value:" + Value + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}
}

