
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ECampType
    {
        NONE = 0,
        /// <summary>
        /// 所有
        /// </summary>
        All = 1,
        /// <summary>
        /// 友方
        /// </summary>
        Friend = 2,
        /// <summary>
        /// 敌人
        /// </summary>
        Enemy = 3,
        /// <summary>
        /// 自己
        /// </summary>
        Self = 4,
    }

} 

