
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Enum_ItemQuality
    {
        None = 0,
        /// <summary>
        /// 普通(白色)
        /// </summary>
        NLevel = 1,
        /// <summary>
        /// 良好 (绿色)
        /// </summary>
        RLevel = 2,
        /// <summary>
        /// 稀有 (蓝色)
        /// </summary>
        SRLevel = 3,
        /// <summary>
        /// 史诗 (紫色)
        /// </summary>
        SSRLevel = 4,
        /// <summary>
        /// 传说 (橙色)
        /// </summary>
        SSSRLevel = 5,
        /// <summary>
        /// 神话 (红色)
        /// </summary>
        URLevel = 6,
    }

} 

