
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Enum_RewardType
    {
        NONE = 0,
        /// <summary>
        /// 固定奖励礼包
        /// </summary>
        Fixed = 1,
        /// <summary>
        /// 随机奖励礼包
        /// </summary>
        Random = 2,
        /// <summary>
        /// 自选礼包
        /// </summary>
        Choice = 3,
    }

} 

