
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Enum_MoveType
    {
        None = 0,
        /// <summary>
        /// 地面移动
        /// </summary>
        Groud = 1,
        /// <summary>
        /// 飞行移动
        /// </summary>
        Air = 2,
    }

} 

