
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Enum_SubType
    {
        /// <summary>
        /// None
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 活动货币
        /// </summary>
        ActivityCoin = 1,
        /// <summary>
        /// 商店货币
        /// </summary>
        ShopCoin = 2,
        /// <summary>
        /// 通用资源
        /// </summary>
        GeneralResource = 3,
        /// <summary>
        /// 经验资源
        /// </summary>
        ExpResource = 4,
        /// <summary>
        /// 体力资源
        /// </summary>
        EnergyResource = 5,
        /// <summary>
        /// vip点数资源
        /// </summary>
        VipResource = 6,
        /// <summary>
        /// 其他资源
        /// </summary>
        OtherResource = 7,
        /// <summary>
        /// 通用加速
        /// </summary>
        GeneralSpeed = 8,
        /// <summary>
        /// 建筑加速
        /// </summary>
        ConstructionSpeed = 9,
        /// <summary>
        /// 科研加速                       
        /// </summary>
        ScientificSpeed = 10,
        /// <summary>
        /// 治疗加速
        /// </summary>
        TreatmentSpeed = 11,
        /// <summary>
        /// 训练加速
        /// </summary>
        TrainingSpeed = 12,
        /// <summary>
        /// 固定宝箱
        /// </summary>
        FixedBox = 13,
        /// <summary>
        /// 随机宝箱
        /// </summary>
        RandomBox = 14,
        /// <summary>
        /// 自选宝箱（选1）
        /// </summary>
        OptionalBox = 15,
        /// <summary>
        /// 多选宝箱
        /// </summary>
        MultiBox = 16,
        /// <summary>
        /// 弓兵
        /// </summary>
        ArcherEquit = 17,
        /// <summary>
        /// 骑兵
        /// </summary>
        CavalryEquit = 18,
        /// <summary>
        /// 盾兵
        /// </summary>
        ShieldEquit = 19,
        /// <summary>
        /// 专属装备
        /// </summary>
        ExclusivseEquit = 20,
        /// <summary>
        /// 英雄碎片
        /// </summary>
        HeroMaterial = 21,
        /// <summary>
        /// 装备碎片
        /// </summary>
        EquitMaterial = 22,
        /// <summary>
        /// 英雄装备强化素材
        /// </summary>
        HeroequitMaterial = 23,
        /// <summary>
        /// 英雄技能强化素材
        /// </summary>
        HeroskillMaterial = 24,
        /// <summary>
        /// 领主装备强化素材
        /// </summary>
        PlayerequitMaterial = 25,
        /// <summary>
        /// 活动消耗素材
        /// </summary>
        ActivityMaterial = 26,
        /// <summary>
        /// 特殊掉落素材
        /// </summary>
        SpecialMaterial = 27,
        /// <summary>
        /// 增益buff
        /// </summary>
        Buff = 28,
        /// <summary>
        /// 抽卡道具
        /// </summary>
        CardDrawing = 29,
        /// <summary>
        /// 活动道具
        /// </summary>
        EventProps = 30,
    }

} 

