
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Enum_ItemType
    {
        None = 0,
        /// <summary>
        /// 货币类
        /// </summary>
        CoinItem = 1,
        /// <summary>
        /// 资源类
        /// </summary>
        ResourceItem = 2,
        /// <summary>
        /// 加速类
        /// </summary>
        SpeedItem = 3,
        /// <summary>
        /// 宝箱类
        /// </summary>
        BoxItem = 4,
        /// <summary>
        /// 装备类
        /// </summary>
        EquitItem = 5,
        /// <summary>
        /// 材料类
        /// </summary>
        MaterialItem = 6,
        /// <summary>
        /// 其他类
        /// </summary>
        OtherItem = 7,
    }

} 

