
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum Enum_UseType
    {
        NONE = 0,
        /// <summary>
        /// 仅展示功能
        /// </summary>
        DisplayUse = 1,
        /// <summary>
        /// 具有使用功能
        /// </summary>
        CanUse = 2,
        /// <summary>
        /// 具有跳转功能
        /// </summary>
        JumpUse = 3,
        /// <summary>
        /// 具有功能操作页面
        /// </summary>
        FunctionUse = 4,
    }

} 

