
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum ETargetType
    {
        NONE = 0,
        /// <summary>
        /// 弓兵英雄
        /// </summary>
        ArcheHero = 1,
        /// <summary>
        /// 弓兵雇佣兵
        /// </summary>
        Arche = 2,
        /// <summary>
        /// 盾兵英雄
        /// </summary>
        ShieldHero = 3,
        /// <summary>
        /// 盾兵雇佣兵
        /// </summary>
        ShieldSoldier = 4,
        /// <summary>
        /// 骑兵英雄
        /// </summary>
        CavalryHero = 5,
        /// <summary>
        /// 骑兵雇佣兵
        /// </summary>
        Cavalry = 6,
        /// <summary>
        /// 大本营（核心建筑）
        /// </summary>
        KeyBuilding = 7,
        /// <summary>
        /// 生产建筑
        /// </summary>
        ProductionBuilding = 8,
        /// <summary>
        /// 存储建筑
        /// </summary>
        StorageBuilding = 9,
        /// <summary>
        /// 功能型建筑
        /// </summary>
        FunctionalBuilding = 10,
        /// <summary>
        /// 城墙
        /// </summary>
        Wall = 11,
        /// <summary>
        /// 防御型建筑（箭塔）
        /// </summary>
        Tower = 12,
    }

} 

