
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Hero : Luban.BeanBase
{
    public Hero(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Name = (string)_obj.GetValue("Name");
        Title = (string)_obj.GetValue("Title");
        HeroType = (Enum_HeroType)(int)_obj.GetValue("HeroType");
        Quality = (Enum_HeroQuality)(int)_obj.GetValue("Quality");
        Position = (string)_obj.GetValue("Position");
        Sex = (Enum_Sex)(int)_obj.GetValue("Sex");
        MoveType = (Enum_MoveType)(int)_obj.GetValue("MoveType");
        AttackType = (Enum_AttackType)(int)_obj.GetValue("AttackType");
        AttackTarget = (Enum_AttackTarget)(int)_obj.GetValue("AttackTarget");
        Mod = (string)_obj.GetValue("Mod");
        Description1 = (string)_obj.GetValue("Description1");
    }

    public static Hero DeserializeHero(JToken _buf)
    {
        return new Hero(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 英雄名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 英雄title
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 英雄类型
    /// </summary>
    public readonly Enum_HeroType HeroType;
    /// <summary>
    /// 英雄品质
    /// </summary>
    public readonly Enum_HeroQuality Quality;
    /// <summary>
    /// 定位
    /// </summary>
    public readonly string Position;
    /// <summary>
    /// 性别
    /// </summary>
    public readonly Enum_Sex Sex;
    /// <summary>
    /// 移动类型
    /// </summary>
    public readonly Enum_MoveType MoveType;
    /// <summary>
    /// 攻击类型
    /// </summary>
    public readonly Enum_AttackType AttackType;
    /// <summary>
    /// 攻击目标
    /// </summary>
    public readonly Enum_AttackTarget AttackTarget;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly string Mod;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description1;


    public const int __ID__ = 2245658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Title:" + Title + ","
        + "HeroType:" + HeroType + ","
        + "Quality:" + Quality + ","
        + "Position:" + Position + ","
        + "Sex:" + Sex + ","
        + "MoveType:" + MoveType + ","
        + "AttackType:" + AttackType + ","
        + "AttackTarget:" + AttackTarget + ","
        + "Mod:" + Mod + ","
        + "Description1:" + Description1 + ","
        + "}";
    }
}
}

