
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum HurtType
    {
        /// <summary>
        /// None
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 物理伤害
        /// </summary>
        PHYSICAL_DAMAGE = 1,
        /// <summary>
        /// 魔法伤害
        /// </summary>
        MAGIC_DAMAGE = 2,
        /// <summary>
        /// 暂无 对应各种属性或者元素攻击
        /// </summary>
        ELEMENTAL_DAMAGE = 4,
    }

} 

