
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Item : Luban.BeanBase
{
    public Item(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemID = (int)_obj.GetValue("ItemID");
        Name = (string)_obj.GetValue("Name");
        Quality = (Enum_ItemQuality)(int)_obj.GetValue("Quality");
        ItemType = (Enum_ItemType)(int)_obj.GetValue("ItemType");
        ItemSubType = (Enum_SubType)(int)_obj.GetValue("ItemSubType");
        Category = (Enum_Order)(int)_obj.GetValue("Category");
        ItemIcon0 = (string)_obj.GetValue("ItemIcon0");
        IsStackable = (bool)_obj.GetValue("IsStackable");
        MaxStack = (int)_obj.GetValue("MaxStack");
        Description = (string)_obj.GetValue("Description");
        RewardID = (int)_obj.GetValue("RewardID");
        UseType = (Enum_UseType)(int)_obj.GetValue("UseType");
        UseMax = (int)_obj.GetValue("UseMax");
        UseLevel = (int)_obj.GetValue("UseLevel");
        TipsID = (int)_obj.GetValue("TipsID");
        IsTimeLimit = (string)_obj.GetValue("IsTimeLimit");
        IsFill = (bool)_obj.GetValue("IsFill");
    }

    public static Item DeserializeItem(JToken _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ItemID;
    /// <summary>
    /// 道具名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly Enum_ItemQuality Quality;
    /// <summary>
    /// 总类型
    /// </summary>
    public readonly Enum_ItemType ItemType;
    /// <summary>
    /// 子类型
    /// </summary>
    public readonly Enum_SubType ItemSubType;
    /// <summary>
    /// 背包分类
    /// </summary>
    public readonly Enum_Order Category;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string ItemIcon0;
    /// <summary>
    /// 能否堆叠
    /// </summary>
    public readonly bool IsStackable;
    /// <summary>
    /// 堆叠最大数量
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 关联奖励ID
    /// </summary>
    public readonly int RewardID;
    /// <summary>
    /// 使用类型
    /// </summary>
    public readonly Enum_UseType UseType;
    /// <summary>
    /// 每天使用上限
    /// </summary>
    public readonly int UseMax;
    /// <summary>
    /// 使用等级要求
    /// </summary>
    public readonly int UseLevel;
    /// <summary>
    /// tipID
    /// </summary>
    public readonly int TipsID;
    /// <summary>
    /// 时限
    /// </summary>
    public readonly string IsTimeLimit;
    /// <summary>
    /// 是否补齐
    /// </summary>
    public readonly bool IsFill;


    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemID:" + ItemID + ","
        + "Name:" + Name + ","
        + "Quality:" + Quality + ","
        + "ItemType:" + ItemType + ","
        + "ItemSubType:" + ItemSubType + ","
        + "Category:" + Category + ","
        + "ItemIcon0:" + ItemIcon0 + ","
        + "IsStackable:" + IsStackable + ","
        + "MaxStack:" + MaxStack + ","
        + "Description:" + Description + ","
        + "RewardID:" + RewardID + ","
        + "UseType:" + UseType + ","
        + "UseMax:" + UseMax + ","
        + "UseLevel:" + UseLevel + ","
        + "TipsID:" + TipsID + ","
        + "IsTimeLimit:" + IsTimeLimit + ","
        + "IsFill:" + IsFill + ","
        + "}";
    }
}
}

