
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class ProjectileParam : Luban.BeanBase
{
    public ProjectileParam(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Res = (string)_obj.GetValue("_res");
        Path = (int)_obj.GetValue("_path");
        Effect = (string)_obj.GetValue("_effect");
        Speed = (int)_obj.GetValue("_speed");
    }

    public static ProjectileParam DeserializeProjectileParam(JToken _buf)
    {
        return new ProjectileParam(_buf);
    }

    /// <summary>
    /// 资源名
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 轨迹
    /// </summary>
    public readonly int Path;
    /// <summary>
    /// 击中特效
    /// </summary>
    public readonly string Effect;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly int Speed;


    public const int __ID__ = 1187110916;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "res:" + Res + ","
        + "path:" + Path + ","
        + "effect:" + Effect + ","
        + "speed:" + Speed + ","
        + "}";
    }
}
}

