
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Reward : Luban.BeanBase
{
    public Reward(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        RewardId = (int)_obj.GetValue("RewardId");
        RewardName = (string)_obj.GetValue("RewardName");
        RewardType = (Enum_RewardType)(int)_obj.GetValue("RewardType");
        RewardParam = (int)_obj.GetValue("RewardParam");
        { var __json0 = _obj.GetValue("RewardDetail"); RewardDetail = new System.Collections.Generic.List<RewardDetai>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { RewardDetai __v0;  __v0 = global::cfg.RewardDetai.DeserializeRewardDetai(__e0);  RewardDetail.Add(__v0); }   }
    }

    public static Reward DeserializeReward(JToken _buf)
    {
        return new Reward(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int RewardId;
    /// <summary>
    /// 奖励名称
    /// </summary>
    public readonly string RewardName;
    /// <summary>
    /// 奖励类型
    /// </summary>
    public readonly Enum_RewardType RewardType;
    /// <summary>
    /// 参数
    /// </summary>
    public readonly int RewardParam;
    public readonly System.Collections.Generic.List<RewardDetai> RewardDetail;


    public const int __ID__ = -1850459313;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RewardDetail) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "RewardId:" + RewardId + ","
        + "RewardName:" + RewardName + ","
        + "RewardType:" + RewardType + ","
        + "RewardParam:" + RewardParam + ","
        + "RewardDetail:" + Luban.StringUtil.CollectionToString(RewardDetail) + ","
        + "}";
    }
}
}

