
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class RewardDetai : Luban.BeanBase
{
    public RewardDetai(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("_id");
        Id_Ref = null;
        Num = (int)_obj.GetValue("_num");
        Weight = (int)_obj.GetValue("_weight");
    }

    public static RewardDetai DeserializeRewardDetai(JToken _buf)
    {
        return new RewardDetai(_buf);
    }

    public readonly int Id;
    public Item Id_Ref;
    public readonly int Num;
    public readonly int Weight;


    public const int __ID__ = -1753914004;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Id_Ref = tables.TbItem.GetOrDefault(Id);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "num:" + Num + ","
        + "weight:" + Weight + ","
        + "}";
    }
}
}

