
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillType
    {
        /// <summary>
        /// None
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 普通攻击
        /// </summary>
        NORMAL_ATTACK = 1,
        /// <summary>
        /// 主动技能
        /// </summary>
        ACTIVE_SKILL = 2,
        /// <summary>
        /// 被动技能
        /// </summary>
        PASSIVE_SKILL = 3,
        /// <summary>
        /// 战斗内永久生效（战斗中所有相关单位修改属性）
        /// </summary>
        AURA_SKILL = 4,
        /// <summary>
        /// 法术牌技能
        /// </summary>
        SPELL_SKILL = 5,
    }

} 

