
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillPassType
    {
        /// <summary>
        /// None
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 无限穿透
        /// </summary>
        PATH = 1,
        /// <summary>
        /// 无视路径
        /// </summary>
        POINT = 2,
        /// <summary>
        /// 会被拦截
        /// </summary>
        PASS = 3,
    }

} 

