
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class SkillTable : Luban.BeanBase
{
    public SkillTable(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("_id");
        Lv = (int)_obj.GetValue("_lv");
        Skill = (int)_obj.GetValue("_skill");
        Name = (string)_obj.GetValue("_name");
        SkillType = (SkillType)(int)_obj.GetValue("_skill_type");
        HurtType = (HurtType)(int)_obj.GetValue("_hurt_type");
        Icon = (string)_obj.GetValue("_icon");
        Prefab = (string)_obj.GetValue("_prefab");
        CastRanage = (int)_obj.GetValue("_cast_ranage");
        { var __json0 = _obj.GetValue("_tag_mask"); TagMask = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  TagMask.Add(__v0); }   }
        DamageRange = (int)_obj.GetValue("_damage_range");
        Preference = (string)_obj.GetValue("_preference");
        LockMethod = (int)_obj.GetValue("_lock_method");
        { var __json0 = _obj.GetValue("_pass_type"); PassType = new System.Collections.Generic.Dictionary<SkillPassType, int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { SkillPassType _k0;  _k0 = (SkillPassType)(int)__e0[0]; int _v0;  _v0 = (int)__e0[1];  PassType.Add(_k0, _v0); }   }
        CollTime = (int)_obj.GetValue("_coll_time");
        { var __json0 = _obj.GetValue("_release_time"); ReleaseTime = new System.Collections.Generic.List<Skill_Animator_State_Time>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { Skill_Animator_State_Time __v0;  __v0 = global::cfg.Skill_Animator_State_Time.DeserializeSkill_Animator_State_Time(__e0);  ReleaseTime.Add(__v0); }   }
        { var __json0 = _obj.GetValue("_effect"); Effect = new System.Collections.Generic.List<int>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { int __v0;  __v0 = (int)__e0;  Effect.Add(__v0); }   }
        Description = (string)_obj.GetValue("_description");
    }

    public static SkillTable DeserializeSkillTable(JToken _buf)
    {
        return new SkillTable(_buf);
    }

    /// <summary>
    /// 暂时没有动画相关的逻辑在里边 待确定 动画独立 技能控制动画 PlayerMaker控制动画 
    /// </summary>
    public readonly int Id;
    public readonly int Lv;
    public readonly int Skill;
    public readonly string Name;
    public readonly SkillType SkillType;
    public readonly HurtType HurtType;
    public readonly string Icon;
    public readonly string Prefab;
    public readonly int CastRanage;
    /// <summary>
    /// 越在前边优先级越高
    /// </summary>
    public readonly System.Collections.Generic.List<string> TagMask;
    /// <summary>
    /// （未定）
    /// </summary>
    public readonly int DamageRange;
    public readonly string Preference;
    public readonly int LockMethod;
    public readonly System.Collections.Generic.Dictionary<SkillPassType, int> PassType;
    public readonly int CollTime;
    /// <summary>
    /// 动作名和释放前后过程
    /// </summary>
    public readonly System.Collections.Generic.List<Skill_Animator_State_Time> ReleaseTime;
    public readonly System.Collections.Generic.List<int> Effect;
    public readonly string Description;


    public const int __ID__ = -704698339;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in ReleaseTime) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "lv:" + Lv + ","
        + "skill:" + Skill + ","
        + "name:" + Name + ","
        + "skillType:" + SkillType + ","
        + "hurtType:" + HurtType + ","
        + "icon:" + Icon + ","
        + "prefab:" + Prefab + ","
        + "castRanage:" + CastRanage + ","
        + "tagMask:" + Luban.StringUtil.CollectionToString(TagMask) + ","
        + "damageRange:" + DamageRange + ","
        + "preference:" + Preference + ","
        + "lockMethod:" + LockMethod + ","
        + "passType:" + Luban.StringUtil.CollectionToString(PassType) + ","
        + "collTime:" + CollTime + ","
        + "releaseTime:" + Luban.StringUtil.CollectionToString(ReleaseTime) + ","
        + "effect:" + Luban.StringUtil.CollectionToString(Effect) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

