
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace cfg
{

public sealed partial class Spell : Luban.BeanBase
{
    public Spell(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("_id");
        SpellQuality = (int)_obj.GetValue("_spell_quality");
        Name = (string)_obj.GetValue("_name");
        SpellType = (SpellType)(int)_obj.GetValue("_spell_type");
        HurtType = (HurtType)(int)_obj.GetValue("_hurt_type");
        Icon = (string)_obj.GetValue("_icon");
        Prefab = (string)_obj.GetValue("_prefab");
        Description = (string)_obj.GetValue("_description");
    }

    public static Spell DeserializeSpell(JToken _buf)
    {
        return new Spell(_buf);
    }

    public readonly int Id;
    public readonly int SpellQuality;
    public readonly string Name;
    public readonly SpellType SpellType;
    public readonly HurtType HurtType;
    public readonly string Icon;
    public readonly string Prefab;
    public readonly string Description;


    public const int __ID__ = 80089352;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "spellQuality:" + SpellQuality + ","
        + "name:" + Name + ","
        + "spellType:" + SpellType + ","
        + "hurtType:" + HurtType + ","
        + "icon:" + Icon + ","
        + "prefab:" + Prefab + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

