
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbBuildsLevel TbBuildsLevel {get; }
    public TbBuilds TbBuilds {get; }
    public TbReward TbReward {get; }
    public TbHero TbHero {get; }
    public TbHeroLevel TbHeroLevel {get; }
    public TbSkillTable TbSkillTable {get; }
    public TbBuff TbBuff {get; }
    public TbMercenary TbMercenary {get; }
    public TbSpell TbSpell {get; }
    public TbConfig TbConfig {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbBuildsLevel = new TbBuildsLevel(loader("tbbuildslevel"));
        TbBuilds = new TbBuilds(loader("tbbuilds"));
        TbReward = new TbReward(loader("tbreward"));
        TbHero = new TbHero(loader("tbhero"));
        TbHeroLevel = new TbHeroLevel(loader("tbherolevel"));
        TbSkillTable = new TbSkillTable(loader("tbskilltable"));
        TbBuff = new TbBuff(loader("tbbuff"));
        TbMercenary = new TbMercenary(loader("tbmercenary"));
        TbSpell = new TbSpell(loader("tbspell"));
        TbConfig = new TbConfig(loader("tbconfig"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbBuildsLevel.ResolveRef(this);
        TbBuilds.ResolveRef(this);
        TbReward.ResolveRef(this);
        TbHero.ResolveRef(this);
        TbHeroLevel.ResolveRef(this);
        TbSkillTable.ResolveRef(this);
        TbBuff.ResolveRef(this);
        TbMercenary.ResolveRef(this);
        TbSpell.ResolveRef(this);
        TbConfig.ResolveRef(this);
    }
}

}

