
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbBuilds
{
    private readonly System.Collections.Generic.Dictionary<int, Builds> _dataMap;
    private readonly System.Collections.Generic.List<Builds> _dataList;
    
    public TbBuilds(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Builds>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Builds>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Builds _v;
            _v = global::cfg.Builds.DeserializeBuilds(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Builds> DataMap => _dataMap;
    public System.Collections.Generic.List<Builds> DataList => _dataList;

    public Builds GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Builds Get(int key) => _dataMap[key];
    public Builds this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

