
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbBuildsLevel
{
    private readonly System.Collections.Generic.Dictionary<int, BuildsLevel> _dataMap;
    private readonly System.Collections.Generic.List<BuildsLevel> _dataList;
    
    public TbBuildsLevel(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuildsLevel>(_buf.Count);
        _dataList = new System.Collections.Generic.List<BuildsLevel>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            BuildsLevel _v;
            _v = global::cfg.BuildsLevel.DeserializeBuildsLevel(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, BuildsLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<BuildsLevel> DataList => _dataList;

    public BuildsLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BuildsLevel Get(int key) => _dataMap[key];
    public BuildsLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

