
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbHeroLevel
{
    private readonly System.Collections.Generic.Dictionary<int, HeroLevel> _dataMap;
    private readonly System.Collections.Generic.List<HeroLevel> _dataList;
    
    public TbHeroLevel(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroLevel>(_buf.Count);
        _dataList = new System.Collections.Generic.List<HeroLevel>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            HeroLevel _v;
            _v = global::cfg.HeroLevel.DeserializeHeroLevel(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, HeroLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroLevel> DataList => _dataList;

    public HeroLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public HeroLevel Get(int key) => _dataMap[key];
    public HeroLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

