
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace cfg
{

public partial class TbSpell
{
    private readonly System.Collections.Generic.Dictionary<int, Spell> _dataMap;
    private readonly System.Collections.Generic.List<Spell> _dataList;
    
    public TbSpell(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Spell>(_buf.Count);
        _dataList = new System.Collections.Generic.List<Spell>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            Spell _v;
            _v = global::cfg.Spell.DeserializeSpell(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
         }
    }


    public System.Collections.Generic.Dictionary<int, Spell> DataMap => _dataMap;
    public System.Collections.Generic.List<Spell> DataList => _dataList;

    public Spell GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Spell Get(int key) => _dataMap[key];
    public Spell this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

