//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Atlas_ab
    {
        public const string BundleName = "atlas.ab";
        public const string Common = "Common";
        public const string Sprite = "Sprite";
    }
    public class Atlas_common_ab
    {
        public const string BundleName = "atlas_common.ab";
        public const string biaoti1 = "biaoti1";
    }
    public class Atlas_sprite_ab
    {
        public const string BundleName = "atlas_sprite.ab";
        public const string ACAWRFV = "ACAWRFV";
        public const string button_ready_off = "button_ready_off";
        public const string Exp_line = "Exp_line";
        public const string Ground = "Ground";
        public const string Hp_frame = "Hp_frame";
        public const string Hp_line = "Hp_line";
        public const string M_line = "M_line";
        public const string Mini_background = "Mini_background";
        public const string Tips_bk_2 = "Tips_bk_2";
    }
    public class Audio_ab
    {
        public const string BundleName = "audio.ab";
        public const string UI_Main3 = "UI_Main3";
    }
    public class Configs_ab
    {
        public const string BundleName = "configs.ab";
        public const string asset_map = "asset_map";
        public const string FrameworkConfig = "FrameworkConfig";
        public const string res_db = "res_db";
        public const string scene_map = "scene_map";
    }
    public class Prefabs_ab
    {
        public const string BundleName = "prefabs.ab";
        public const string TestPanel = "TestPanel";
        public const string UI_Main = "UI_Main";
    }
    public class Scenes_ab
    {
        public const string BundleName = "scenes.ab";
        public const string Game = "Game";
        public const string MainScene = "MainScene";
    }
}
